import numpy as np
import re

BohrInAngstrom = 0.529177249 # TODO import from somewhere

FCHK_TAGS = {
    "NoAtoms": "Number of atoms",
    "Charge": "Charge",
    "Multiplicity": "Multiplicity",
    "NoElectrons": "Number of electrons",
    "NoAlphaElectrons": "Number of alpha electrons",
    "NoBetaElectrons": "Number of beta electrons",
    "AtomicNumbers": "Atomic numbers",
    "CartCoords": "Current cartesian coordinates", # Bohr radii
    "NBasis": "Number of basis functions",
    "HCore": "Core Hamiltonian Matrix",# Only upper triangle is printed due to Complex Conjugate symmetry, AO Basis?
    "SCFEnergy": "SCF Energy",
    "AlphaMoCoeff": "Alpha MO coefficients",
    "BetaMoCoeff": "Beta MO coefficients", # May not exist
    "ShellToAtomMap" : "Shell to atom map",
    "ShellAngMom" : "Shell types",
    "ECPMatrix": "Effective Core Potential Matrix",
    "Comment":"XXXXXXXXXXX", #No delimiter for this but it is parsed
    "Basis":"XXXXXXXXXXX"#No delimiter for this but it is parsed
    }

#This almost certainly exists but i couldnt find a quick way to get at it
TABLE_OF_ELEMENTS = {
    1:'H',
    2:'He',
    3:'Li',
    4:'Be',
    5:'B',
    6:'C',
    7:'N',
    8:'O',
    9:'F',
    17:'Cl',
    36:'Kr',
    29:'Cu'
}
def loadTextMatrix(filename):
    with open(filename, 'r') as file:
        matrix = []
        for line in file:
            row = [float(value) for value in line.strip().split() if value]
            matrix.append(row)
        return np.array(matrix)

def loadBinary2Eri(filename,NBasis):
    # loads a file called XXX2eri.bin aka file 21.0 in qchem. 
    # This is generated by the SAVE_AO_INTEGRALS 1 rem setting
    # ln -s QChemNEGF/3-MCHO/h2_Test/scratch/h2/21.0 H22eri.bin
    try:
        eri = np.fromfile(filename,dtype=np.float64)
        eriLength = len(eri)
        eriReshapeLength = int(eriLength**0.25)
        if eriLength != eriReshapeLength*eriReshapeLength*eriReshapeLength*eriReshapeLength:
            eriReshapeLength +=1 #rounding
        if eriLength != eriReshapeLength*eriReshapeLength*eriReshapeLength*eriReshapeLength:
            eriReshapeLength -=2 #rounding
        if eriLength != eriReshapeLength*eriReshapeLength*eriReshapeLength*eriReshapeLength:
            return np.zeros(shape=(0,0))
        #assert(eriLength == eriReshapeLength*eriReshapeLength*eriReshapeLength*eriReshapeLength)

        eri = eri[:eriReshapeLength*eriReshapeLength*eriReshapeLength*eriReshapeLength].reshape((eriReshapeLength*eriReshapeLength,eriReshapeLength*eriReshapeLength))
    except FileNotFoundError as e:
        print(f"Could not open file: {filename}")
        return np.zeros(shape=(0,0))
    return eri

def load1EInt(filename):
    # loads a file called XXX1eInt.dat aka file NEGF_hmat.tmp in qchem. 
    # This is generated by NEGF with a modified code to generate even in analysis mode line 2089 in scfman.C 
    # ln -s QChemNEGF/3-MCHO/h2_Test/scratch/h2/NEGF_hmat.tmp H21eInt.bin
    mat = loadTextMatrix(filename).flatten()
    length = len(mat)
    squareLength = int(length**0.5)
    if length != squareLength*squareLength:
        squareLength += 1
    if length != squareLength*squareLength:
        squareLength -= 2
    assert(length == squareLength*squareLength)
    return mat.reshape(squareLength,squareLength)

def loadVector(file,typeCast,N):
    #Assumes that reading to the end of the line wont go over N, i.e the vector is terminated by a new line
    matrix = []
    for line in file:
        row = [typeCast(value) for value in line.strip().split() if value]
        matrix += row
        if len(matrix) >= N:
            break
    if len(matrix) > N:
        print(f"Overread matrix?, Len:{len(matrix)}, N:{N}")
    return np.array(matrix)

def makeSquareFromLT(mat,NBasis):
    #Makes a square matrix from a lower triangular vectoriesed one
    hcoreVectorIter = iter(mat)
    ret = np.zeros(shape=(NBasis,NBasis)) # For now these are always real
    for i in range(NBasis):
        for j in range(i+1):
            ret[i,j] = next(hcoreVectorIter)
            ret[j,i] = ret[i,j]

    return ret





def loadFCHK(filename):
    #Parses a file called XX.fchk from QCHEM e.g.
    #ln -s QChemNEGF/3-MCHO/h2_Test/h2.in.fchk H2.fchk
    #In principle this can parse any FCHK file

    

    #Main Parsing function
    Params = {}
    with open(filename, 'r') as file:
        Params["Comment"] = next(file).rstrip()
        Params["Basis"] = next(file).split()[-1].rstrip()
        for line in file:
            
            for TagName, TagString in FCHK_TAGS.items():
                if line.startswith(TagString):
                    if "N=" in line:
                        #Vector
                        n_match = re.search(r"N=\s*(\d+)", line)
                        if n_match:
                            n = int(n_match.group(1))
                            if "R" in line.split():
                                Params[TagName] = loadVector(file,float,n)
                            elif "I" in line.split():
                                Params[TagName] = loadVector(file,int,n)
                            else:
                                print(f"Unknown Array dataType in {TagString}")
                        else: 
                            print(f"Identified {TagString} as a vector but couldnt determine size")
                    else:
                        #Not a vector
                        splitLine = line.split()
                        if "I" in splitLine:
                            #Integer
                            IIndex = splitLine.index("I")
                            Params[TagName] = int(splitLine[IIndex+1])
                        elif "R" in splitLine:
                            #Real number
                            RIndex = splitLine.index("R")
                            Params[TagName] = float(splitLine[RIndex+1])
                        else:
                            print(f"Unknown dataType in {TagString}")

    #Some cleanup needed
    if not "BetaMoCoeff" in Params:
        Params["BetaMoCoeff"] = Params["AlphaMoCoeff"]
    
    #Make HCore square
    # hcoreVector = Params["HCore"]
    # hcoreVectorIter = iter(hcoreVector)
    # NBasis = Params["NBasis"]
    # Params["HCore"] = np.zeros(shape=(NBasis,NBasis)) # For now these are always real
    # for i in range(NBasis):
    #     for j in range(i+1):
    #         Params["HCore"][i,j] = next(hcoreVectorIter)
    #         Params["HCore"][j,i] = Params["HCore"][i,j]
    Params["HCore"] = makeSquareFromLT(Params["HCore"],Params["NBasis"])
    if "ECPMatrix" in Params:
        Params["ECPMatrix"] = makeSquareFromLT(Params["ECPMatrix"],Params["NBasis"])
    #Reshape Atomic coords
    Params["CartCoords"] = Params["CartCoords"].reshape((-1,3))
    return Params

def loadQChem(outputName):
    success = True
    S=F=D=fchkParams=oneEInts=eri = None
    try:
        S = loadTextMatrix(outputName+"Smat.dat")
        F = loadTextMatrix(outputName+"FAmat.dat")
        D = loadTextMatrix(outputName+"DAmat.dat")
        fchkParams = loadFCHK(outputName + ".fchk")
        eri = loadBinary2Eri(outputName + "2eri.bin",fchkParams["NBasis"])
        
        try:
            oneEInts = load1EInt(outputName + "1eInt.dat")*0.5 # Unclear but this is needed
            #No exception thrown
            if "HCore" in fchkParams and not "ECPMatrix" in fchkParams:
                #ECP means this equality is not true, But also in general its not true since the FCHK and internally have different ordering
                #FCHK has data until the 8th decimal place. So allow an error in this
                #assert(np.allclose(fchkParams["HCore"], oneEInts,rtol=2e-8)) 
                pass
            elif not "HCore" in fchkParams:
                fchkParams["HCore"] = oneEInts
        except FileNotFoundError as e:
            print(f"Cant load HCORE fchkHCORE may be ordered wrong, Filename:{outputName + "1eInt.dat"}")
            if not "HCore" in fchkParams:
                print("Couldnt find 1EIntFile and fchk does not contain this")
            oneEInts = fchkParams["HCore"]
    except FileNotFoundError as e:
        print(e)
        eri = np.zeros((0,0))
        success = False
    if len(eri) == 0:
        success = False
    return (S,F,D,eri,oneEInts,fchkParams,success)

def generatePyscfAtomString(fchkParams):
    atomstring = ""
    
    for atomicNumber,Pos in zip(fchkParams["AtomicNumbers"],fchkParams["CartCoords"]):
        atomstring += f"{TABLE_OF_ELEMENTS[atomicNumber]} {Pos[0]*BohrInAngstrom} {Pos[1]*BohrInAngstrom} {Pos[2]*BohrInAngstrom};"
    return atomstring

def loadWithRevQCMagic(outputName):
    """Returns a density matrix for use as an initial guess and a configured pySCF mol from the qchem file"""
    from qcmagic.interfaces.converters.qchem import qchem_output_to_configuration_state
    from qcmagic.interfaces.converters.pyscf import configuration_to_mol
    from qcmagic.core.cspace.basis.basisshell import BasisType
    from qcmagic.core.sspace.single_determinant import SingleDeterminant

    config, state = qchem_output_to_configuration_state(outputName+".out",0.0)
    cbs = config.get_subconfiguration("ConvolvedBasisSet")
    libintOccMOs = state.occupied_coefficients
    pyscfOccMOs=  cbs.convert_coefficient_matrices(
        libintOccMOs, BasisType.BT_LIBINT, BasisType.BT_PYSCF
    )
    pyscfState = SingleDeterminant(state.n_electrons, config, holo = False,
                                    occ_coeffs = pyscfOccMOs)
    pyscfMol = configuration_to_mol(config)
    #Need to set the ECP correctly
    fchkParams = loadFCHK(outputName + ".fchk")
    if "ECPMatrix" in fchkParams:
        pyscfMol.ecp = fchkParams["Basis"]
        pyscfMol.build()
    return (pyscfState.density_matrices[0],pyscfMol)
def computeQChemToPyscfPermutation(outputName,fchkParams):
    from qcmagic.interfaces.converters.qchem import qchem_output_to_configuration_state
    from qcmagic.core.cspace.basis.basisshell import BasisType

    if fchkParams is None:
        fchkParams = loadFCHK(outputName + ".fchk")

    
    config, state = qchem_output_to_configuration_state(outputName+".out",0.0)
    cbs = config.get_subconfiguration("ConvolvedBasisSet")

    permutation=  cbs.convert_coefficient_matrices(
        [np.identity(fchkParams["NBasis"])], BasisType.BT_QCHEM, BasisType.BT_PYSCF
    )[0]
    #Do not ask why but this is needed
    AOBoundaries = cbs.function_indices_for_item_starts
    AOBoundaries.append(cbs.n_functions) # stop index
    for idx in range(len(AOBoundaries)-1):
        if cbs.basis_items[idx][0].atomic_number == 29 and fchkParams["Basis"] == "LANL2DZ": # Copper. Identify based on atomic number, other options available, We know you have your choice of providers, thank you for choosing Atomic number to serve you today
            #Permute the first and second AO. This is probably the 1s and 2s. 
            permutation[AOBoundaries[idx],AOBoundaries[idx]] =permutation[AOBoundaries[idx]+1,AOBoundaries[idx]+1] = 0
            permutation[AOBoundaries[idx]+1,AOBoundaries[idx]] =permutation[AOBoundaries[idx],AOBoundaries[idx]+1] = 1
    return (permutation,cbs,state)





	

#analysis("/home/bence/Ciss/Calculations/CHO_CuSmall/choAndCuSmall3SP.qcout")
#analysis("/home/bence/Ciss/QChemNEGF/3-MCHO/Kr_Test/Kr.out")

def figureOutPermutation(hcoreQchem, hcoreOther, tolerance = 1e-6):
    #Figures out how to permute the rows and columns of hcoreQchem to get hcoreOther, if possible
    permuteMatrix = np.identity(len(hcoreOther))
    hcoreQchemPermuted = hcoreQchem
    toBreak = True
    while toBreak:# GOTOs dont exist even though this would be a good time for one
        toBreak = False
        for rowQchem,rowOther in zip(hcoreQchemPermuted,hcoreOther):
            for idxOther,elemOther in enumerate(rowOther):
                if not np.isclose(elemOther,rowQchem[idxOther],rtol=tolerance):
                    #Not the same so find its pair
                    foundPair = False
                    idxs = np.where(np.isclose(rowQchem[idxOther:], elemOther,rtol=tolerance))[0]
                    if len(idxs) > 0:
                        idx = idxs[0]+idxOther
                        foundPair = True
                    assert(foundPair)
                    qchemIndex1 = np.where(permuteMatrix[:,idx] == 1)[0][0]
                    qchemIndex2 = np.where(permuteMatrix[:,idxOther] == 1)[0][0]
                    permuteMatrix[qchemIndex1,idxOther] = 1
                    permuteMatrix[qchemIndex2,idxOther] = 0
                    permuteMatrix[qchemIndex1,idx] = 0
                    permuteMatrix[qchemIndex2,idx] = 1
                    print(f"Element: {elemOther} at {idxOther} did not match {rowQchem[idxOther]}, Instead this is at {idx}")
                    print(f"Matrix now has ({qchemIndex1},{idxOther}) and ({qchemIndex2},{idx})")
                    #Applies the swap to the permutation matrix
                    toBreak = True
                if toBreak:
                    break
            if toBreak:
                    break
        hcoreQchemPermuted = permuteMatrix @ hcoreQchem @ permuteMatrix
    print("Succesfully aligned the two matrices")
    assert(np.allclose(hcoreQchemPermuted,hcoreOther,rtol=tolerance))
    return permuteMatrix

def reorderQChemFCHKMOCoeffsToPYSCF(fchkParams):
    shellTypes = fchkParams["ShellAngMom"]
    totalAO = 0
    for shellMom in shellTypes:
        totalAO += abs(shellMom)*2 +1
    assert(totalAO == fchkParams["NBasis"])
    permuteMatrix = np.zeros(totalAO)
    AOCount = 0
    for shellMom in shellTypes:
        L = abs(shellMom)
        #Cartesian spherical functions, i think
        if L > 5:
            assert(False) # not possible from fchk file apparently
        if L == 0:
            permuteMatrix[AOCount,AOCount] = 1
            AOCount+=1
        elif L==1:
            permuteMatrix[AOCount,AOCount] = 1
            permuteMatrix[AOCount+1,AOCount+1] = 1
            permuteMatrix[AOCount+2,AOCount+2] = 1
            AOCount+=3
        elif L==2:
            isPure = False
            if shellMom < 0:
                isPure = True
            if (shellMom == -1):
                assert(False)# Dont know how to deal with this but this shouldn't come up
                isPure = False # SP hybrid
        #TODO



                

                