#ifndef BASISMANAGER_H
#define BASISMANAGER_H

#include "global.h"
#include "enums.h"
//Note we cannot include linalg.h here since it depends on us
#include "linalgForwardDeclarations.h"
#include "complexmatrixbuffer.h"
#include <Eigen/Core>
#include <Eigen/Sparse>
#include <memory>
#include <string>
#include <shared_mutex>




//Must have symmetry tag in order to be able to revert from a Spin Blocked Basis

class BasisManager
{
public:
    //TODO move to enums
    enum class possibleTags
    {
        LowdinBasis,
        ABlock,
        // ABBlock,
        // BABlock,
        BBlock,
        NullBasis,// The "" basis, Orthonormal and has no links elsewhere
    };
private:
    friend int testBasisTransforms();
    friend int testBuiltinBasisTransforms();
    class Basis;
    struct Path;
    std::list<std::shared_ptr<Basis>> m_BasisList;
    std::shared_mutex m_basisLock;
    BasisManager();
    ~BasisManager();


    BasisManager(const BasisManager& other) = delete;
    BasisManager(BasisManager&& other) = delete;
    BasisManager& operator=(const BasisManager& other) = delete;
    BasisManager& operator=(BasisManager&& other) = delete;

    //Used to validate that a basis does not have tags. But also used to remove all tags from a basis. Generally the latter
    static std::string sanitizeInput(std::string input, bool allowTags /* = false*/);

    void sanitizeForTags(const std::string& basisString);
    std::shared_ptr<Basis> lookupBasis(const std::string& basisString, bool allowAutoGenerated);
    std::shared_ptr<Basis> lookupBasis(const std::string& from, const std::string& to, bool allowAutoGenerated);
    std::vector<std::pair<std::string,std::string>> generateLinkElements(const std::string& from, const std::string& to);
    std::vector<std::shared_ptr<Basis>> findPath(std::shared_ptr<Basis> start, const std::string from, const std::string to);
    std::shared_ptr<Basis> findLink(std::string from, std::string to);
    std::shared_ptr<Basis> generateDirectLinkAlongPath(const std::vector<std::shared_ptr<Basis>>& path);
    // New basis derived from parent basis. This means the metric is autodetermined,
    // Returns the lock aswell so that modifications to the returned basis can be performed without race conditions. Freely discard this if not needed.
    std::pair<std::shared_ptr<BasisManager::Basis>,std::unique_lock<std::shared_mutex>> addBasis(const std::string& name, const std::string& parent,const Eigen::MatrixXcd& parentToHereForwardTransform, bool isAutoGenerated, const Eigen::MatrixXcd* hereToParentForwardTransformation = nullptr);
    std::shared_ptr<Basis> addProjection(const std::string& name, const std::string& parent,const Eigen::MatrixXcd& parentToHereForwardTransform, bool isAutoGenerated, const Eigen::MatrixXcd* hereToParentForwardTransformation = nullptr);
    std::shared_ptr<Basis> addProjectionOrthogonal(const std::string& name, const std::string& parent,const Eigen::MatrixXcd& parentToHereForwardTransform, bool isAutoGenerated, const Eigen::MatrixXcd* hereToParentForwardTransformation = nullptr);
    //Specifies that the new basis is orthogonal.
    std::pair<std::shared_ptr<BasisManager::Basis>,std::unique_lock<std::shared_mutex>> addOrthogonalBasis(const std::string& name, const std::string& parent, const Eigen::MatrixXcd& parentToHereForwardTransform, bool isAutoGenerated, const Eigen::MatrixXcd* hereToParentForwardTransformation = nullptr);
    //Used to make sure everything is deleted, Only testing
    size_t getBasisObjects();



    Eigen::MatrixXcd makeLowdin(std::shared_ptr<Basis> bas);
    Eigen::MatrixXcd makeLowdinInverse(std::shared_ptr<Basis> bas);
    //These functions are probably what you intended
    Eigen::MatrixXcd makeAlpha(std::shared_ptr<Basis> bas);
    Eigen::MatrixXcd makeBeta(std::shared_ptr<Basis> bas);

    /*These functions are probably not what you indended. It is the pseudoinverse of makeAlpha.
     * Note that this does NOT create any beta quantities.
     * This could make RHF quantities for VECTORS only. For matrices this is not possible
     * Consider the Alpha vector |1>. Inverting this we would like to get |10> + |01>. This can be done
     * Now consider the Alpha matrix |1><1| Inverting this(Alpha always on the left) we would like to get |10><10| + |01><01|.
     * Instead we find we get (|10> + |01>)(<10| + <01|) which is not the same. Hence the difficulty.
     */
    Eigen::MatrixXcd makeAlphaInv(std::shared_ptr<Basis> bas);
    Eigen::MatrixXcd makeBetaInv(std::shared_ptr<Basis> bas);
    void makeNullBasis();


public:
    template<typename T>
    struct BasisTransform
    {
        MatrixBufferObject<T> transform;
        bool isIdentity = false; // allows the multiplication to be skipped, if isIdentity == True then transform cannot be dereferenced
        operator bool() const
        {//returns true if it is good
            return !transform.isEmpty() || (transform.isEmpty() && isIdentity);
        }
        T& operator*()
        {
            assert(!transform.isEmpty());
            return *transform;
        }
        MatrixBufferObject<T>& operator->()
        {
            assert(!transform.isEmpty());
            return transform;
        }
    };

    static inline const std::string LowdinOrthogonaliseBasis = "_LB"; //Restricted Suffix that means to go into the Lowdin Basis associated with a given basis

    //Note that Going to the basis you obtain what you probably intended. Going back probably note. See makeAlphaInv.
    static inline const std::string Alpha_Block = "_AAB"; //Restricted Suffix that means to get the Alpha-Alpha Block of a matrix. In the future spin will be an explicit thing
    // static inline const std::string Alpha_Beta_Block = "_ABB"; //Restricted Suffix that means to get the Alpha-Beta Block of a matrix. In the future spin will be an explicit thing
    // static inline const std::string Beta_Alpha_Block = "_BAB"; //Restricted Suffix that means to get the Alpha-Beta Block of a matrix. In the future spin will be an explicit thing
    static inline const std::string Beta_Block = "_BBB"; //Restricted Suffix that means to get the Alpha-Beta Block of a matrix. In the future spin will be an explicit thing




    static BasisManager& getInstance();

    //Gives the transformation between two basis and the specified index types. Complex conjugation?
    // If i is the old and mu is the new basis
    //|e_\mu} = L_\mu^{i} |e_i>. Stored as L_{i\mu}
    //Therefore a direct basis object is transformed by multiplication on the RIGHT!
    //For this reason the returned matrix should be used as v_mu = v_i Mat^i_mu
    //AllowProjectedRaising allows raising indices by returning, raising, projecting. Effectively this is the stored raising operator.
    BasisTransform<Eigen::MatrixXcd> getTransform(const std::string& from, enums::IndexType fromIndex, const std::string& to, enums::IndexType toIndex, bool AllowProjectedRaising = false);

    BasisTransform<Eigen::SparseMatrix<complexType>> getTransform_S(const std::string& from, enums::IndexType fromIndex, const std::string& to, enums::IndexType toIndex, bool AllowProjectedRaising = false);


    //New basis with no links
    //Lowering Metric: S_{\bar{i}j}
    void addBasis(std::string name, const Eigen::MatrixXcd& loweringMetric);

    //Orthogonal under the conventional (complex) inner product.
    void addOrthogonalBasis(std::string name, long dim);


    //New basis derived from parent basis. This means the metric is autodetermined, If the transformation if non-square and does not commute with the metric a warning is raised.
    //|e_\mu} = L_\mu^{i} |e_i>. Expected to be stored as L_{i\mu }
    void addBasis(std::string name, const std::string& parent,const Eigen::MatrixXcd& parentToHereForwardTransform);

    //New projection derived from parent basis. This disables using the metric to lower and raise indices.
    //|e_\mu} = L_\mu^{i} |e_i>. Expected to be stored as L_{i\mu }
    void addProjection(std::string name, const std::string& parent,const Eigen::MatrixXcd& parentToHereForwardTransform);
    //Same as above but specifies that the resultant basis is orthogonal.
    void addProjectionOrthogonal(std::string name, const std::string& parent,const Eigen::MatrixXcd& parentToHereForwardTransform);

    //Specifies that the new basis is orthogonal. If the transformation if non-square and does not commute with the metric a warning is raised.
    //|e_\mu} = L_\mu^{i} |e_i>. Expected to be stored as L_{i\mu}
    void addOrthogonalBasis(std::string name, const std::string& parent, const Eigen::MatrixXcd& parentToHereForwardTransform);


    //Temporary bases that are deleted by the shared_ptr. Storing the string beyond the lifetime of the shared_ptr is UB
    //New temporary basis with no links
    [[nodiscard]]std::shared_ptr<std::string> addTemporaryBasis(const Eigen::MatrixXcd& loweringMetric);

    //New temporary basis from parent
    [[nodiscard]]std::shared_ptr<std::string> addTemporaryBasis(const std::string& parent, const Eigen::MatrixXcd& parentToHereForwardTransform);

    //New temporary basis that is specified to be orthogonal
    [[nodiscard]]std::shared_ptr<std::string> addTemporaryOrthogonalBasis(const std::string& parent, const Eigen::MatrixXcd& parentToHereForwardTransform);

    //TODO temporary projection basis
    //TODO should not ever need this
    LoweringMetric getMetric(const std::string& basis);

    bool isOrthogonal(const std::string& basis);


    //static for ease of use in destructors. deletes all generated bases which are derived from name. E.g. Name_LB and Name_AAB
    static void deleteBasis(const std::string& name);

    //static for ease of use in destructors
    static void deleteAllBasis();

    static std::string buildCanonicalBasisString(std::string basis, std::vector<possibleTags> tags);
    static std::string buildCanonicalBasisString(std::string basis); // same as above but extracts the tags
    static std::vector<possibleTags> checkForTags(std::string basisString, bool* success = nullptr);
    static std::string removeSpinTags(std::string basisString, possibleTags* deletedTag = nullptr);
    static bool hasSpinBlockTag(const std::string& basisName); // returns true if it has the AA tag or BB tag ONLY

    //This should really go into an algorithms header or something
    template<typename T>
    static bool contains(const std::vector<T>& vec, const T& val)
    {
        return std::find(vec.begin(),vec.end(),val) != vec.end();
    }
    static bool exists(const std::string& basis);
    static bool isProjection(const std::string& basisName);

};







#endif // BASISMANAGER_H
