#include "basismanager.h"
#include "linalg.h"

#include <algorithm>
#include <utility>
constexpr bool traceBasisCreations = true;

#define TRACEBASISDELETIONS
#ifdef TRACEBASISDELETIONS
std::atomic<size_t> numberOfObjects = 0;
#endif
inline bool XOR(bool a, bool b)
{
    /* Truth table
     * A | B | Result
     * T | T | F
     * T | F | T
     * F | T | T
     * T | T | F
     */
    return a != b;
}
struct BasisManager::Basis
{
    //Identitification
    std::string name;
    std::string parentName; // If parent == name then there is no parent

    //Graph structure
    std::list<std::shared_ptr<Basis>> linkedNodes; //Other Nodes that can be transformed to

    //Basis details
    Eigen::MatrixXcd loweringMetric;
    Eigen::MatrixXcd raisingMetric;
    // If i is the parent and mu is the new basis
    // bas->parentToHereDirect = |e_\mu} = L_\mu^{i} |e_i>. Expected to be stored as L_{i\mu}
    Eigen::MatrixXcd parentToHereDirect;
    //If parentToHereDirect is square then this is the inverse of that matrix.
    //If not then it is such that L^{i}_{\mu}L^{\nu}_{i} = \delta_{\mu}^{\nu}. Note that \mu may have different number of indices than i
    // Eigen::MatrixXcd parentToHereDual; // L^{\nu}_{i} stored as L_{i \nu} // NOTE THIS IS DIFFERENT TO CONVENTION

    // bas->hereToParentDirect = |e_i} = L_i^{\mu} |e_\mu>. Stored as L_{\mu i}
    Eigen::MatrixXcd hereToParentDirect;
    //If parentToHereDirect is square then this is the inverse of that matrix.
    //If not then it is such that L^{i}_{\mu}L^{\mu}_{j} = \delta_{j}^{i}. Note that \mu may have different number of indices than \mu.
    // Eigen::MatrixXcd hereToParentDual;//L^{i}_{\mu} stored as L_{\mu i} // NOTE THIS IS DIFFERENT TO CONVENTION

    //If i has more indices than mu then \delta_{\mu}^{\nu} is the Identity matrix. However \delta_{j}^{i} Is a 'partial' Identity matrix with the same number of ones.

    bool isOrthoNormal = false; // Under conventional complex inner product
    bool isAutoGenerated = false; // Describes that this node has been generated to shortcut a basis transformation. It may also be a tagged node

    /* Projections in non-orthogonal bases have bad properties. For example AO->Mol0->Raise->AO =/= AO->Raise.
     * This is because the raising and lowering metric of the projected space are not inverses of one another
     * For a projection therefore we disable transformation of indices via the metric. Therefore things like the adjoint aren't allowed.
     * If the projection commutes with the metric, E.g. Lowdin basis, then there is no need to tag it as a projection.
     * We try to detect this and issue a warning if a projection is not marked as such when it should be
     */
    bool isProjection = false;

    //Utility function that constructs parentToHereDirect .. etc from parentToHereDirect. If parentToHereDirect is not invertible a warning will be issued.
    //Ideally we'd want to reduce the apparent dimension of the basis. This cant be done however since we must preserve the desired basis vectors.
    //This can lead to zeros in Eigenvalues computed in this basis etc. all this stemming from the fact that the basis has a null space
    /* As an example Consider the transformation
     * [[1,1],
     *  [1,1]]*0.5
     * The vector [[1],[1]] gets mapped to [[1],[1]]. But [[1],[-1]] gets mapped to [[0],[0]]. Therefore this transformation is not invertible
     * We could change the matrix to be
     * [[1,1]]*0.5 this would map [[1],[1]] to [[1]] and [[1],[-1]] gets mapped to [[0]]. This correctly conveys the dimensionality of the space but is a different transformation
     */

    static void generateTransformations(Eigen::MatrixXcd& parentToHereDirect/*, Eigen::MatrixXcd& parentToHereDual */,Eigen::MatrixXcd& hereToParentDirect/*, Eigen::MatrixXcd& hereToParentDual*/)
    {//                                                   n*p matrix. m = min(n,p)
        long m = std::min(parentToHereDirect.rows(), parentToHereDirect.cols());

        Eigen::BDCSVD<Eigen::MatrixXcd> SVD(parentToHereDirect, Eigen::ComputeThinU | Eigen::ComputeThinV);

        const Eigen::MatrixXcd& U = SVD.matrixU(); //Old x singular
        const Eigen::MatrixXcd& V = SVD.matrixV(); //new x singular
        //Sorted in decreasing order
        Eigen::VectorXd S = SVD.singularValues(); // singular x singular
        Eigen::VectorXd SInv = SVD.singularValues().cwiseInverse(); // singular x singular
        if (SVD.rank() != m)
        {
            logger().printf("Transformation has misleading dimension. Consider providing a non square transformation. Rank %li, at most %li\n",SVD.rank(),m);
            for (Eigen::Index sIdx = SVD.rank(); sIdx < SInv.rows(); ++sIdx)
            {
                SInv(sIdx) = 0;
            }
        }

        parentToHereDirect = U * S.asDiagonal() * V.adjoint(); // L^{i}_{\mu} as L_{i\mu}
        hereToParentDirect = V * SInv.asDiagonal() * U.adjoint(); // L^{\mu}_{i} as L_{\mu i}
        Eigen::MatrixXcd shouldBeID = parentToHereDirect*hereToParentDirect;
        Eigen::MatrixXcd shouldBeID2 = hereToParentDirect*parentToHereDirect;
        Eigen::MatrixXcd shouldBeID3 = V.adjoint()*V;
        Eigen::MatrixXcd shouldBeID4 = S.asDiagonal() * V.adjoint() * V * SInv.asDiagonal();
        Eigen::MatrixXcd shouldBeID5 = U*U.adjoint();
        Eigen::MatrixXcd shouldBeID6 = U * S.asDiagonal() * V.adjoint() * V * SInv.asDiagonal() * U.adjoint();
        return;
        // parentToHereDual =  hereToParentDirect.transpose(); // L^{\nu}_{i} as L_{i \nu}
        // hereToParentDual = parentToHereDirect.transpose(); // L^{i}_{\mu} as L_{\mu i}

        //Note that:
        //parentToHereDirect.transpose() * parentToHereDual = V.conjugate() * S.asDiagonal() * U.transpose() * U.conjugate() * S.cwiseInverse().asDiagonal() * V.transpose = I



    }

    Basis()
    {
#ifdef TRACEBASISDELETIONS
        ++numberOfObjects;
#endif
    }
    ~Basis()
    {
#ifdef TRACEBASISDELETIONS
        --numberOfObjects;
#endif
    }
    Basis(const Basis& other) = delete;
    Basis(Basis&& other) = default;
    Basis& operator=(const Basis& other) = delete;
    Basis& operator=(Basis&& other) = default;

    std::unique_lock<std::shared_mutex> removeNode(std::unique_lock<std::shared_mutex>&& lock, const std::string& nodeName)
    {
        for (auto l = linkedNodes.begin(); l != linkedNodes.end();)
        {
            if ((*l)->name == nodeName)
                l = linkedNodes.erase(l);
            else
                ++l;
        }
        if (parentName == nodeName)
            parentName = name;
        return std::move(lock);
    }

    std::unique_lock<std::shared_mutex> cleanupMyself(std::unique_lock<std::shared_mutex>&& lock)
    {
        //Remove this from all linked nodes.
        //What to do about dangling parentNames? On the one hand it is useful since the parent->Here transform is not invalidated if parent is deleted.
        //On the other hand the Here->Parent transform probably should be since the Parent metric may not be known anymore
        //If there are no more nodes with the parent Name then we must remove the parent and invalidate the transform.
         // modifying the graph so need a unique lock
        for (auto l = linkedNodes.begin(); l != linkedNodes.end();l++)
        {
            lock = (*l)->removeNode(std::move(lock),name);
        }
        linkedNodes.clear();
        return std::move(lock);

    }
    std::unique_lock<std::shared_mutex> cleanupAll(std::unique_lock<std::shared_mutex>&& lock)
    {//Removes all my children and deletes the reference to the parent. Use only when the entire graph will be cleared
        linkedNodes.clear();
        return std::move(lock);
    }

    bool operator ==(const Basis& other) const
    {
        return name == other.name && parentName == other.parentName;
    }

    bool links(const std::string& A, const std::string& B)
    {
        if (A == B && A == name)
            return true;
        if (A == name && B == parentName)
            return true;
        if (B == name && A == parentName)
            return true;
        return false;
    }

};




std::vector<BasisManager::possibleTags> BasisManager::checkForTags(std::string basisString, bool* success/* = nullptr*/)
{

    std::vector<possibleTags> listOfTags;
    if (success)
        *success = true;

    bool foundSpinBlockTag = false;
    bool foundLBTag = false;

    size_t foundLoc;

    while((foundLoc = basisString.find(LowdinOrthogonaliseBasis)) != std::string::npos)
    {
        if (foundLBTag && success)
            *success = false;
        foundLBTag = true;
        basisString.erase(foundLoc,LowdinOrthogonaliseBasis.size());
        listOfTags.push_back(possibleTags::LowdinBasis);
    }


    while ((foundLoc = basisString.find(Alpha_Block)) != std::string::npos)
    {
        if (foundSpinBlockTag && success)
            *success = false;
        foundSpinBlockTag = true;
        basisString.erase(foundLoc,Alpha_Block.size());
        listOfTags.push_back(possibleTags::ABlock);
    }

    while ((foundLoc = basisString.find(Beta_Block)) != std::string::npos)
    {
        if (foundSpinBlockTag && success)
            *success = false;
        foundSpinBlockTag = true;
        basisString.erase(foundLoc,Beta_Block.size());
        listOfTags.push_back(possibleTags::BBlock);
    }

    return listOfTags;
}

BasisManager::BasisManager()
{
    makeNullBasis();
}

BasisManager::~BasisManager()
{
    deleteAllBasis();
    if (getBasisObjects() != 1)
    {
        //This can happen if there are circular references, which is likely if the graph is broken.
        logger().log("Not all basis objects deleted: ", getBasisObjects());
    }
}

void BasisManager::sanitizeForTags(const std::string &basisString)
{
    std::string errorString = "Tags present in basis string: " + basisString;
    releaseAssert(checkForTags(basisString).size() == 0,errorString);
}



size_t BasisManager::getBasisObjects()
{
#ifdef TRACEBASISDELETIONS
    return numberOfObjects;
#endif
    return 0;
}

std::string BasisManager::sanitizeInput(std::string input, bool allowTags = false)
{
    std::vector<possibleTags> tags = checkForTags(input);
    for (const auto& t: tags)
    {
        switch(t)
        {
        case possibleTags::LowdinBasis:
        {
            size_t pos = input.find(LowdinOrthogonaliseBasis);
            input.erase(pos,LowdinOrthogonaliseBasis.size());
            if (!allowTags)
                logger().log("Forbidden Lowdin basis tag found. Removing to make ", input);
            break;
        }
        case possibleTags::ABlock:
        {
            size_t pos = input.find(Alpha_Block);
            input.erase(pos,Alpha_Block.size());
            if (!allowTags)
                logger().log("Forbidden Alpha_Block basis tag found. Removing to make ", input);
            break;
        }
        case possibleTags::BBlock:
        {
            size_t pos = input.find(Beta_Block);
            input.erase(pos,Beta_Block.size());
            if (!allowTags)
                logger().log("Forbidden Beta_Block basis tag found. Removing to make ", input);
            break;
        }
        case possibleTags::NullBasis:
            break;
        }
    }

    if (input.size() == 0)
        if (!allowTags)
            logger().log("the '' basis is restricted. Please choose another basis");
    return input;
}

Eigen::MatrixXcd BasisManager::makeLowdin(std::shared_ptr<Basis> bas)
{
    Eigen::MatrixXcd metric = bas->loweringMetric;
    //Eigen matrix square root exists but Unsupported. So lets do it ourselves
    Eigen::SelfAdjointEigenSolver<Eigen::MatrixXcd> es(metric,Eigen::ComputeEigenvectors);
    Eigen::MatrixXcd eVecs = es.eigenvectors();
    Eigen::VectorXd eVals = es.eigenvalues();
    numType numericalPrecision = 5e-14;
    for (auto& e : eVals)
    {
        if (e < numericalPrecision)
        {
            logger().log("Small EigenValue in Lowdin, Implement different sized matrices",e);
            e = 0;
        }
        else
            e = 1./std::sqrt(e);
    }
    //This is the correct way to transform a direct basis object
    //S_{\bar{\nu}\mu} = L^{\bar{j}}_{\bar{\nu}} L^{i}_{\mu} S_{\bar{j}i} = I
    //eVecs * eVals.asDiagonal() * eVecs.adjoint() = L^{i}_{\mu} stored as L_{i\mu} = L_{\bar{nu}\bar{j}} because it is Hermitian.
    //This can be seen by S^{-1/2} S S^{-1/2} = I
    return eVecs * eVals.asDiagonal() * eVecs.adjoint();
}

Eigen::MatrixXcd BasisManager::makeLowdinInverse(std::shared_ptr<Basis> bas)
{
    Eigen::MatrixXcd metric = bas->loweringMetric;
    //Eigen matrix square root exists but Unsupported. So lets do it ourselves
    Eigen::SelfAdjointEigenSolver<Eigen::MatrixXcd> es(metric,Eigen::ComputeEigenvectors);
    Eigen::MatrixXcd eVecs = es.eigenvectors();
    Eigen::VectorXd eVals = es.eigenvalues();
    numType numericalPrecision = 5e-14;
    for (auto& e : eVals)
    {
        if (e < numericalPrecision)
        {
            logger().log("Small EigenValue in Lowdin, Implement different sized matrices",e);
            e = 0;
        }
        else
            e = std::sqrt(e);
    }
    //This is the correct way to transform a direct basis object
    //S_{\bar{\nu}\mu} = L^{\bar{j}}_{\bar{\nu}} L^{i}_{\mu} S_{\bar{j}i} = I
    //eVecs * eVals.asDiagonal() * eVecs.adjoint() = L^{i}_{\mu} stored as L_{i\mu} = L_{\bar{nu}\bar{j}} because it is Hermitian.
    //This can be seen by S^{-1/2} S S^{-1/2} = I
    return eVecs * eVals.asDiagonal() * eVecs.adjoint();
}

Eigen::MatrixXcd BasisManager::makeAlpha(std::shared_ptr<Basis> bas)
{
    //bas is the non Alpha basis
    long numberOfDirect = bas->loweringMetric.cols();
    long numberOfDual = bas->raisingMetric.rows();
    // Cant yet handle when this is different
    assert(numberOfDirect == numberOfDual);
    releaseAssert(numberOfDual %2 == 0, "Can only spin block an even matrix. Something went wrong");
    Eigen::MatrixXcd ret(numberOfDual,numberOfDual/2);
    ret.setZero();
    for (long i = 0; i < numberOfDual/2; i++)
    {
        ret(2*i,i) = 1; // Note the requirement that L^{i}_{\mu} stored as L_{i\mu}
    }
    //Could also use Eigen::PermutationMatrix
    return ret;// Inverse?
}

Eigen::MatrixXcd BasisManager::makeBeta(std::shared_ptr<Basis> bas)
{
    long numberOfDirect = bas->loweringMetric.cols();
    long numberOfDual = bas->raisingMetric.rows();
    // Cant yet handle when this is different
    assert(numberOfDirect == numberOfDual);
    releaseAssert(numberOfDual %2 == 0, "Can only spin block an even matrix. Something went wrong");
    Eigen::MatrixXcd ret(numberOfDual,numberOfDual/2);
    ret.setZero();
    for (long i = 0; i < numberOfDual/2; i++)
    {
        ret(2*i+1,i) = 1; // Note the requirement that L^{i}_{\mu} stored as L_{i\mu}
    }
    //Could also use Eigen::PermutationMatrix
    return ret;// Inverse?
}

Eigen::MatrixXcd BasisManager::makeAlphaInv(std::shared_ptr<Basis> bas)
{
    long numberOfDirect = bas->loweringMetric.cols();
    long numberOfDual = bas->raisingMetric.rows();
    // Cant yet handle when this is different
    assert(numberOfDirect == numberOfDual);
    Eigen::MatrixXcd ret(numberOfDual/2,numberOfDual);
    ret.setZero();
    for (long i = 0; i < numberOfDual/2; i++)
    {
        ret(i,2*i) = 1; // Note the requirement that L^{i}_{\mu} stored as L_{i\mu}
    }
    //Could also use Eigen::PermutationMatrix
    return ret;// Inverse?
}

Eigen::MatrixXcd BasisManager::makeBetaInv(std::shared_ptr<Basis> bas)
{
    long numberOfDirect = bas->loweringMetric.cols();
    long numberOfDual = bas->raisingMetric.rows();
    // Cant yet handle when this is different
    assert(numberOfDirect == numberOfDual);
    Eigen::MatrixXcd ret(numberOfDual/2,numberOfDual);
    ret.setZero();
    for (long i = 0; i < numberOfDual/2; i++)
    {
        ret(i,2*i+1) = 1; // Note the requirement that L^{i}_{\mu} stored as L_{i\mu}
    }
    //Could also use Eigen::PermutationMatrix
    return ret;// Inverse?
}

void BasisManager::makeNullBasis()
{
    auto bas = std::make_shared<Basis>();
    bas->name = "";
    bas->parentName = "";
    bas->isOrthoNormal = true;
    std::unique_lock<std::shared_mutex> lock(m_basisLock);
    m_BasisList.emplace_back(std::move(bas));
}




std::shared_ptr<BasisManager::Basis> BasisManager::generateDirectLinkAlongPath(const std::vector<std::shared_ptr<Basis> > &path)
{
    assert(path.size() > 2);// If it is a one it is already a direct link and this should not be called
    //Path should contain: Parent->Child1->Child2 at least. Parent->Child1 should have already been resolved

    const std::string& startName = path.front()->name;
    const std::string& destName = path.back()->name;

    std::string currentName = startName;
    std::string nextName = path[1]->name; // lookahead to know whether we go to the parent or somewhere else

    Eigen::MatrixXcd AccumulatedForward;
    Eigen::MatrixXcd AccumulatedBackward;
    bool Initialised = false;
    // If i is the parent and mu is the new basis
    //|e_\mu} = L_\mu^{i} |e_i>. Expected to be stored as L_{i\mu}
    for (size_t it = 0; it < path.size(); it++)
    {

        if (path[it]->name != path[it]->parentName)
        {
            if (Initialised)
            {
                if (nextName == path[it]->parentName)
                {
                    AccumulatedForward = AccumulatedForward*path[it]->hereToParentDirect;
                    AccumulatedBackward = path[it]->parentToHereDirect*AccumulatedBackward;
                    currentName = nextName;
                    if (it < path.size()-2) // look at the element after the parent. The parent is next
                        nextName = path[it+2]->name;
                }
                else if (nextName == path[it]->name)
                {
                    AccumulatedForward = AccumulatedForward*path[it]->parentToHereDirect;
                    AccumulatedBackward = path[it]->hereToParentDirect*AccumulatedBackward;
                    currentName = nextName;
                    if (it < path.size()-1) // look at the next element
                        nextName = path[it+1]->name;
                }
                //If the node is a V shape i.e.      4 -> 1 -> 2
                //                                          -> 3
                //And the goal is to get from 3->2 then 3->1->2 is a valid path but when on 1. nextName = 2 =/= 1 =/= 4
            }
            else
            {
                if (nextName == path[it]->parentName)
                {
                    AccumulatedForward = path[it]->hereToParentDirect;
                    AccumulatedBackward = path[it]->parentToHereDirect;
                    currentName = nextName;
                    if (it < path.size()-2)
                        nextName = path[it+2]->name;
                    Initialised = true;
                }
                else if (nextName == path[it]->name)
                {
                    AccumulatedForward = path[it]->parentToHereDirect;
                    AccumulatedBackward = path[it]->hereToParentDirect;
                    currentName = nextName;
                    if (it < path.size()-1)
                        nextName = path[it+1]->name;
                    Initialised = true;
                }
            }
        }


    }
    releaseAssert(currentName == destName,"Path is Broken, not reached end");
    return addBasis(destName,startName,AccumulatedForward,true,&AccumulatedBackward).first;
}

struct BasisManager::Path
{
    std::vector<std::shared_ptr<BasisManager::Basis>> path;
    Path operator+(const std::shared_ptr<BasisManager::Basis>& newNode)
    {
        Path ret = *this;
        ret.path.push_back(newNode);
        return ret;
    }
};
//Find the path less the tags
std::vector<std::shared_ptr<BasisManager::Basis>> BasisManager::findPath(std::shared_ptr<Basis> start, const std::string from, const std::string to)
{
    Path resultantPath;
    std::shared_lock<std::shared_mutex> lock(m_basisLock);
    //No direct connection so must enumerate the graph

    // This is basically Dijsktra but we check if we have been to a node before.
    // This check can be eliminated by prestoring a list of visited nodes and the fastest ways to get to them but this requires the Node->vistedNodes lookup or a search.
    // Either way none of this will be a bottleneck
    std::list<Path> searchStack;
    searchStack.push_back({{start}});

    while (searchStack.size() > 0)
    {
        Path currentPath = searchStack.front();
        searchStack.pop_front();
        for (const auto& l : currentPath.path.back()->linkedNodes)
        {
            if (!l->isAutoGenerated && !contains(currentPath.path,l))
            {
                if (l->name == to)
                {
                    resultantPath = currentPath + l;
                    return resultantPath.path;
                }
                searchStack.push_back(currentPath + l);
            }
        }
    }

    return resultantPath.path;
}
std::vector<std::pair<std::string, std::string> > BasisManager::generateLinkElements(const std::string &fromInput, const std::string &toInput)
{
    //Generates the basic elements that must exist for the builtin basis objects.
    std::vector<std::pair<std::string, std::string> > ret;

    std::vector<possibleTags> tagsFrom = checkForTags(fromInput);
    std::vector<possibleTags> tagsTo = checkForTags(toInput);
    std::string sanitisedFrom = sanitizeInput(fromInput,true);
    std::string sanitisedTo = sanitizeInput(toInput,true);
    //TODO Lowdin Basis should be its own node so something like 1_LB_AAB should have 1_LB as its parent not 1
    if (tagsFrom.size() > 0)
    {
        ret.emplace_back(std::make_pair(sanitisedFrom,fromInput));
    }
    if (tagsTo.size() > 0)
    {
        ret.emplace_back(std::make_pair(sanitisedTo,toInput));
    }
    if (sanitisedFrom != sanitisedTo)
        ret.emplace_back(std::make_pair(sanitisedFrom,sanitisedTo));

    return ret;
}

std::shared_ptr<BasisManager::Basis> BasisManager::findLink(std::string fromInput, std::string toInput)
{
    //This function is not guaranteed to be atomic if it needs to add a transformation.
    //In principle if two people in different threads call this and cause it to generate a transformation,
    //the transformation could be added twice. If a transformation is added by this while another thread deletes it the parent basis link is a use after free.

    // Returns the element that links `from' and `to'. If it doesnt exist, generates it
    // Effectively this is a breadth first search through the graph.
    // The first pass checks if there are any direct connections between the given nodes. If so we choose that.
    // If not then autogenerated paths are ignored and a Breadth first search is conducted to find the path between the two nodes.
    // When adding a transformation to the graph it is checked that this path is impossible so there is only one unique path. I.e. the graph should be acyclic once the autogenerated edges have been removed

    auto linkNode = lookupBasis(fromInput,toInput,true); // linkNode links from and to. Or if from == to then linkNode has name == from
    if (linkNode)
    {
        return linkNode;
    }    

    std::vector<possibleTags> tagsFrom = checkForTags(fromInput);
    std::vector<possibleTags> tagsTo = checkForTags(toInput);
    std::string sanitisedFrom = sanitizeInput(fromInput,true);
    std::string sanitisedTo = sanitizeInput(toInput,true);
    if (!lookupBasis(sanitisedFrom,false))
    {
        // logger().log("Requested a transformation from a basis that does not exist",sanitisedFrom);
        return nullptr;
    }
    if (!lookupBasis(sanitisedTo,false))
    {
        // logger().log("Requested a transformation to a basis that does not exist",sanitisedTo);
        return nullptr;
    }

    //Try putting the tags in canonical order
    if (tagsFrom.size() > 0 || tagsTo.size() > 0)
    {
        std::sort(tagsFrom.begin(),tagsFrom.end());
        std::sort(tagsTo.begin(),tagsTo.end());
        std::string trialFrom = buildCanonicalBasisString(sanitisedFrom,tagsFrom);
        std::string trialTo = buildCanonicalBasisString(sanitisedTo,tagsTo);

        linkNode = lookupBasis(trialFrom,trialTo,true); // linkNode links from and to. Or if from == to then linkNode has name == from
        if (linkNode)
        {
            //Add an alias for this Basis for faster lookup
            addBasis(toInput,fromInput,linkNode->parentToHereDirect,true,&linkNode->hereToParentDirect);
            return linkNode;
        }
        //Will become cached next time with the correct name, This way all possible permutations will just use the cache
        fromInput = trialFrom;
        toInput = trialTo;
    }
    //Generates the special bases one by one

    std::vector<std::pair<std::string, std::string> > neededTransforms = generateLinkElements(fromInput,toInput);
    if (neededTransforms.size() > 1)
    {
        for (const auto& p : neededTransforms)
        {
            if (!findLink(p.first,p.second))
                return nullptr;
        }
    }
    else if (neededTransforms.size() == 1)
    {
        const auto& p = neededTransforms[0];
        if (p.first != fromInput)
        {
            assert(p.second != toInput);
            if (!findLink(p.first,p.second))
                return nullptr;
        }
        else
            assert(p.second == toInput);
    }
    else
        releaseAssert(false, "Unhandled case");




    linkNode = lookupBasis(fromInput,toInput,false); // linkNode links from and to. Or if from == to then linkNode has name == from
    if (linkNode)
        return linkNode;
    //If this failed this means we need to do a path search

    bool toInputExists = (bool)lookupBasis(toInput,false);
    bool fromInputExists = (bool)lookupBasis(fromInput,false);
    assert(fromInputExists); // I think this should always exist

    linkNode = lookupBasis(fromInput,toInputExists ? toInput : sanitisedTo,false); //direct connection


    std::shared_ptr<BasisManager::Basis> resultantBasis;
    if (!linkNode)
    { //No direct connection, Do the lookup
        std::vector<std::shared_ptr<Basis>> resultantPath;
        std::shared_ptr<Basis> start = lookupBasis(fromInput,false);
        if (!start)
            return nullptr;
        resultantPath = findPath(start,fromInput, toInputExists ? toInput : sanitisedTo);
        if (resultantPath.size() == 0)
        {
            //Could not find path
            return nullptr;
        }
        resultantBasis = generateDirectLinkAlongPath(resultantPath);
    }
    else
        resultantBasis = linkNode;
    if (toInputExists)
        return resultantBasis;

    //toInput does not exist so path is only until sanitisedTo

    std::shared_ptr<Basis> end = lookupBasis(sanitisedTo,false);
    if (!end)
        return nullptr;

    //It is assumed that the Tags commute. I.e. doing one first and then the other is the same as other other way around
    Eigen::MatrixXcd AccumulatedForward;
    if (resultantBasis->isOrthoNormal)
        AccumulatedForward = resultantBasis->loweringMetric;
    else if (fromInput == sanitisedTo)
    {
        AccumulatedForward = Eigen::MatrixXcd::Identity(resultantBasis->loweringMetric.cols(),resultantBasis->loweringMetric.cols());
    }
    else
    {
        if (resultantBasis->parentName == fromInput)
            AccumulatedForward = resultantBasis->parentToHereDirect;
        else
            AccumulatedForward = resultantBasis->hereToParentDirect;
    }
    Eigen::MatrixXcd AccumulatedBackward;
    if (resultantBasis->isOrthoNormal)
        AccumulatedBackward = resultantBasis->loweringMetric;
    else if (fromInput == sanitisedTo)
    {
        AccumulatedBackward = Eigen::MatrixXcd::Identity(resultantBasis->loweringMetric.cols(),resultantBasis->loweringMetric.cols());
    }
    else
    {
        if (resultantBasis->parentName == fromInput)
            AccumulatedBackward = resultantBasis->hereToParentDirect;
        else
            AccumulatedBackward = resultantBasis->parentToHereDirect;
    }

    for(const auto& t : tagsTo)
    {
        switch (t)
        {
        case possibleTags::LowdinBasis:
        {
            if (end->isProjection)
                return nullptr;// Cannot make Lowdin basis from a projection basis since the metric is inconsistent.
            Eigen::MatrixXcd LB = makeLowdin(end);
            AccumulatedForward *=  LB;
            LB = makeLowdinInverse(end);
            AccumulatedBackward =  LB * AccumulatedBackward ;
            break;
        }
        case possibleTags::ABlock:
        {
            Eigen::MatrixXcd AA = makeAlpha(end);
            AccumulatedForward *=  AA;
            AA = makeAlphaInv(end);
            AccumulatedBackward = AA *AccumulatedBackward;
            break;
        }
        case possibleTags::BBlock:
        {
            Eigen::MatrixXcd BB = makeBeta(end);
            AccumulatedForward *=  BB;
            BB = makeBetaInv(end);
            AccumulatedBackward = BB * AccumulatedBackward;
            break;
        }
        default:
            releaseAssert(false, "Not Implemented Switch case");
            break;
        }
    }
    /* Truth table
     * sanitisedFrom == sanitisedTo | sanitisedTo == toInput | sanitisedFrom == fromInput | isOneStep
     *               T              |             T          |               T            |   F --Not possible since this means fromInput == toInput and therefore we should have already found the basis and solved it
     *               T              |             T          |               F            |   T -- One step  fromInput->toInput
     *               T              |             F          |               T            |   T -- One step  fromInput->toInput
     *               T              |             F          |               F            |   F -- Two steps fromInput->sanitisedTo->toInput
     *               F              |             X          |               X            |   F -- At least two steps sanitisedFrom->sanitisedTo unless sanitisedTo == toInput && sanitisedFrom == fromInput and sanitisedFrom->sanitisedTo are neighbours
     */
    assert(fromInput != toInput);
    assert(!(lookupBasis(sanitisedFrom,sanitisedTo,false) && sanitisedTo == toInput && sanitisedFrom == fromInput)); // The last case

    bool isOneStep = sanitisedFrom == sanitisedTo && XOR(sanitisedTo == toInput,sanitisedFrom == fromInput);
    bool toInputisProjection = false; if (auto b = lookupBasis(toInput,false)) toInputisProjection = b->isProjection; // https://en.cppreference.com/w/cpp/language/if.html
    bool fromInputisProjection =false; if (auto b = lookupBasis(fromInput,false)) fromInputisProjection = b->isProjection;

    std::pair<std::shared_ptr<BasisManager::Basis>,std::unique_lock<std::shared_mutex>> bas;
    if (isOneStep && contains(tagsTo, possibleTags::LowdinBasis))
        bas = addOrthogonalBasis(toInput,fromInput,AccumulatedForward, false ,&AccumulatedBackward);
    else if (contains(tagsTo, possibleTags::LowdinBasis))
        bas = addOrthogonalBasis(toInput,fromInput,AccumulatedForward, true ,&AccumulatedBackward);
    else
        bas = addBasis(toInput,fromInput,AccumulatedForward,isOneStep ? false : true,&AccumulatedBackward);

    if (bas.first->isAutoGenerated)
        bas.first->isProjection = toInputisProjection; // we hold the lock so cant do any more lookups
    if (tagsTo.size() > 0) // autogenerated by us
        bas.first->isProjection = fromInputisProjection;
    return bas.first;
}


std::shared_ptr<BasisManager::Basis> BasisManager::lookupBasis(const std::string &inString, bool allowAutoGenerated)
{
    //O(n) which is fine
    std::string basisString = buildCanonicalBasisString(inString);
    std::shared_lock<std::shared_mutex> lock(m_basisLock);
    for (const auto& bas : m_BasisList)
    {
        if (!allowAutoGenerated && bas->isAutoGenerated)
            continue;
        if (bas->name == basisString)
            return bas;
    }
    return nullptr;
}

std::shared_ptr<BasisManager::Basis> BasisManager::lookupBasis(const std::string &fromIn, const std::string& toIn, bool allowAutoGenerated)
{
    //O(n) which is fine
    std::string from = buildCanonicalBasisString(fromIn);
    std::string to = buildCanonicalBasisString(toIn);
    std::shared_lock<std::shared_mutex> lock(m_basisLock);
    for (const auto& bas : m_BasisList)
    {
        if (!allowAutoGenerated && bas->isAutoGenerated)
            continue;
        if (bas->links(from,to))
            return bas;
    }
    return nullptr;
}


bool BasisManager::hasSpinBlockTag(const std::string &basisName)
{
    std::vector<possibleTags> tags = checkForTags(basisName);
    bool hasAATag = contains(tags,possibleTags::ABlock);
    bool hasBBTag = contains(tags,possibleTags::BBlock);
    releaseAssert(!(hasAATag && hasBBTag) ,"Matrix cannot have both tags");
    return hasAATag || hasBBTag;
}

bool BasisManager::exists(const std::string &basis)
{
    return BasisManager::getInstance().lookupBasis(basis,false) != nullptr;
}

bool BasisManager::isProjection(const std::string &basisName)
{
    auto bas = BasisManager::getInstance().lookupBasis(basisName,true);
    if (!bas)
        return false;
    return bas->isProjection;
}

BasisManager &BasisManager::getInstance()
{
    static BasisManager b;
    return b;
}

BasisManager::BasisTransform<Eigen::MatrixXcd> BasisManager::getTransform(const std::string &from, enums::IndexType fromIndex, const std::string &to, enums::IndexType toIndex,  bool AllowProjectedRaising)
{

    //Special case the eigenValue type and the invalid type
    if (fromIndex == toIndex && (fromIndex == enums::IndexType::eigenValue || fromIndex == enums::IndexType::invalid))
    {
        //This index does not need to be transformed
        return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),true};
    }
    if (fromIndex == toIndex && from == to)
    {
        //This index does not need to be transformed
        return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),true};
    }
    std::shared_ptr<Basis> bas = findLink(from,to);
    if (!bas) return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),false};

    std::shared_ptr<Basis> basTo = lookupBasis(to,false);
    if (!basTo) return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),false};
    // If allow projectedRaising then this is not an error. It can be well defined to do this if your aim is to insert an overlap matrix between indexes being contracted.
    // e.g. v^\bar{i} S_{\bar{i}j}v^j vs v_j v^j where v_j = v^\bar{i} S_{\bar{i}j} with all indexes summing over the reduced basis set.
    if (basTo->isProjection && fromIndex != toIndex && !AllowProjectedRaising)
    {
        //If the from basis is not a projection than this error can be recovered by transforming the index first and then projecting.
        std::shared_ptr<Basis> basFrom = lookupBasis(from,false);
        if (!basFrom) return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),false};
        if (basFrom->isProjection)
            // Could be recovered if this is a tree like transformation that goes through a full basis intermediate, Too complicated right now, Do it in two steps
        {
            //Nice error message
            logger().log("Could not convert indices in basis", from);
            logger().log("fromIndex", fromIndex);
            logger().log("toIndex", toIndex);
            return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),false};
        }

        //basFrom is not a projection. Construct the transformation in two parts.
        BasisTransform<Eigen::MatrixXcd> transformationPart1 = getTransform(from,fromIndex,from,toIndex,AllowProjectedRaising);
        BasisTransform<Eigen::MatrixXcd> transformationPart2 = getTransform(from,toIndex,to,toIndex,AllowProjectedRaising);
        if (!transformationPart1 || !transformationPart2)
            return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),false};
        if (transformationPart1.isIdentity)
            return transformationPart2;
        else if (transformationPart2.isIdentity)
            return transformationPart1;
        else
        {
            *transformationPart1 *= *transformationPart2;
            return transformationPart1;
        }

    }
    // If i is the old and mu is the new basis
    //|e_\mu} = L_\mu^{i} |e_i>. Stored as L_{i\mu}
    //Therefore a direct basis object is transformed by multiplication on the right!
    BasisTransform<Eigen::MatrixXcd> transformation;
    if (from != to)
    {
        //Having to and from backwards means we need the inverse transform.
        //Transforming a dual basis object also means we need the inverse transform
        //Therefore two inverses make a not inverse. I.e. XOR
        bool InverseTransform = to == bas->parentName;
        bool DualTransform = fromIndex == enums::IndexType::dual || fromIndex == enums::IndexType::improperDual;
        bool isEigenValueOrInvalid = fromIndex == enums::IndexType::eigenValue || fromIndex == enums::IndexType::invalid;

        if (InverseTransform && DualTransform)
            transformation.transform.get() = bas->parentToHereDirect.transpose();
        else if (InverseTransform && !DualTransform)
            transformation.transform.get() = bas->hereToParentDirect;
        else if (!InverseTransform && DualTransform)
            transformation.transform.get() = bas->hereToParentDirect.transpose();
        else if (!InverseTransform && !DualTransform)
            transformation.transform.get() = bas->parentToHereDirect;
        else if (isEigenValueOrInvalid) // This is the case if the index == eigenvalue or invalid
            transformation.isIdentity = true;//Never reached
        else
            releaseAssert(false, "Unhandled case");
    }
    else
    {
        transformation.isIdentity = true;
    }
    //The overall order would be something like SLS^{-1} but L is identity so this simplifies
    if (fromIndex == toIndex && transformation.isIdentity)
        return transformation;
    if (!transformation.isIdentity)
    {
        switch (fromIndex)
        {
        case enums::IndexType::direct:// Default case
        case enums::IndexType::dual://Handled already when deciding on the transform to use.
            break;
        case enums::IndexType::improperDirect:
        case enums::IndexType::improperDual:
            //Need to take the conjugate
            transformation.transform.get() = transformation.transform.get().conjugate();
            break;
        case enums::IndexType::eigenValue:
        case enums::IndexType::invalid:
            break;
        default:
            releaseAssert(false,"Unhandled switch case");
        }
        if (fromIndex == toIndex)
            return transformation; // No metrics needed
    }

    //From index != toIndex
    //S_{\bar{i}j} S^{i\bar{j}}
    bas = lookupBasis(to,false); // we care about the properties of the to basis now. This != bas potentially. E.g. it is the parent basis
    if (!bas)
        return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),false};
    if (bas->isOrthoNormal)
    {
        if (transformation.isIdentity)
            //Not needed to construct an empty transformation but it will give errors later if someone ignores the identity tag
            return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),true};
        else
            return transformation;
    }

    //Not orthonormal
    if (fromIndex == enums::IndexType::direct && toIndex == enums::IndexType::improperDual)
    {    
        if (transformation.isIdentity)
        {
            transformation.transform.get() = bas->raisingMetric;
            transformation.isIdentity = false;
            return transformation;
        }
        else
        {
            BasisTransform<Eigen::MatrixXcd> temp;
            temp.transform->noalias() = transformation.transform.get()*bas->raisingMetric;
            return temp;
        }
    }
    else if (fromIndex == enums::IndexType::improperDual && toIndex == enums::IndexType::direct)
    {
        if (transformation.isIdentity)
        {
            transformation.transform.get() = bas->loweringMetric;
            transformation.isIdentity = false;
            return transformation;
        }
        else
        {
            BasisTransform<Eigen::MatrixXcd> temp;
            temp.transform->noalias() = transformation.transform.get()*bas->loweringMetric;
            return temp;
        }
    }
    else if (fromIndex == enums::IndexType::dual && toIndex == enums::IndexType::improperDirect)
    {
        if (transformation.isIdentity)
        {
            transformation.transform.get() = bas->loweringMetric.transpose();
            transformation.isIdentity = false;
            return transformation;
        }
        else
        {
            BasisTransform<Eigen::MatrixXcd> temp;
            temp.transform->noalias() = transformation.transform.get()*bas->loweringMetric.transpose();
            return temp;
        }
    }
    else if (fromIndex == enums::IndexType::improperDirect && toIndex == enums::IndexType::dual)
    {
        if (transformation.isIdentity)
        {
            transformation.transform.get() = bas->raisingMetric.transpose();
            transformation.isIdentity = false;
            return transformation;
        }
        else
        {
            BasisTransform<Eigen::MatrixXcd> temp;
            temp.transform->noalias() = transformation.transform.get()*bas->raisingMetric.transpose();
            return temp;
        }
    }
    else
    {
        logger().log("Unhandled index transform case");
        return BasisTransform<Eigen::MatrixXcd> {MatrixBufferObject<Eigen::MatrixXcd>::getEmpty(),false};
    }
}

BasisManager::BasisTransform<Eigen::SparseMatrix<complexType>> BasisManager::getTransform_S(const std::string &from, enums::IndexType fromIndex, const std::string &to, enums::IndexType toIndex,  bool AllowProjectedRaising)
{
    BasisTransform<Eigen::MatrixXcd> denseTransform = getTransform(from,fromIndex,to,toIndex,AllowProjectedRaising);
    if (!denseTransform)
        return BasisTransform<Eigen::SparseMatrix<complexType>> {MatrixBufferObject<Eigen::SparseMatrix<complexType>>::getEmpty(),false};
    if (denseTransform.isIdentity)
        return BasisTransform<Eigen::SparseMatrix<complexType>> {MatrixBufferObject<Eigen::SparseMatrix<complexType>>::getEmpty(),true};

    BasisTransform<Eigen::SparseMatrix<complexType>> temp;
    temp.transform.get() = denseTransform.transform->sparseView();
    temp.isIdentity = false; // Not needed
    return temp;
}



void BasisManager::addBasis(std::string name, const Eigen::MatrixXcd &loweringMetric)
{
    //New basis with no links
    name = sanitizeInput(name);
    auto foundBas = lookupBasis(name,true);
    if (foundBas)
    {
        logger().log("Basis already exists, not adding", name);
        return;
    }
    if constexpr(traceBasisCreations)
        logger().log("Creating basis from metric with name", name);

    auto bas = std::make_shared<Basis>();
    bas->name = name;
    bas->parentName = name;
    bas->loweringMetric = loweringMetric;
    bas->raisingMetric = loweringMetric.inverse();//TODO be clever about zeros
    std::unique_lock<std::shared_mutex> lock(m_basisLock);
    BasisManager::getInstance().m_BasisList.emplace_back(std::move(bas));
}

void BasisManager::addOrthogonalBasis(std::string name, long dim)
{
    name = sanitizeInput(name);
    auto foundBas = lookupBasis(name,true);
    if (foundBas)
    {
        logger().log("Basis already exists, not adding", name);
        return;
    }
    if constexpr(traceBasisCreations)
        logger().log("Creating orthogonal basis: " + name + ", from metric with dimension", dim);
    auto bas = std::make_shared<Basis>();
    bas->name = name;
    bas->parentName = name;
    bas->isOrthoNormal = true;
    bas->loweringMetric = Eigen::MatrixXcd::Identity(dim,dim);
    bas->raisingMetric = Eigen::MatrixXcd::Identity(dim,dim);

    std::unique_lock<std::shared_mutex> lock(m_basisLock);
    BasisManager::getInstance().m_BasisList.emplace_back(std::move(bas));
}

void BasisManager::addBasis(std::string name, const std::string &parent, const Eigen::MatrixXcd &parentToHereForwardTransform)
{
    name = sanitizeInput(name);
    auto foundBas = lookupBasis(name,true);
    if (foundBas)
    {
        logger().log("Basis already exists, not adding", name);
        return;
    }
    if (parent == "")
    {
        logger().log("The null basis, '' is restricted");
        return;
    }
    auto bas = addBasis(name,parent,parentToHereForwardTransform,false);
    //Raise warning if the raising metric implied and calculated are not consistent.
    Eigen::MatrixXcd ShouldBeID = bas.first->loweringMetric*bas.first->raisingMetric;
    numType error = (ShouldBeID - Eigen::MatrixXcd::Identity(ShouldBeID.rows(),ShouldBeID.cols())).norm();
    if (error > 1e-11)
        logger().log("Warning added basis transformation and raising/lowering metric are inconsistent, Error", error);

}

void BasisManager::addProjection(std::string name, const std::string &parent, const Eigen::MatrixXcd &parentToHereForwardTransform)
{
    name = sanitizeInput(name);
    auto foundBas = lookupBasis(name,true);
    if (foundBas)
    {
        logger().log("Basis already exists, not adding", name);
        return;
    }
    if (parent == "")
    {
        logger().log("The null basis, '' is restricted");
        return;
    }
    addProjection(name,parent,parentToHereForwardTransform,false);
}

void BasisManager::addOrthogonalBasis(std::string name, const std::string &parent, const Eigen::MatrixXcd &parentToHereForwardTransform)
{
    name = sanitizeInput(name);
    auto foundBas = lookupBasis(name,true);
    if (foundBas)
    {
        logger().log("Basis already exists, not adding", name);
        return;
    }
    auto bas = addOrthogonalBasis(name,parent,parentToHereForwardTransform,false);
    //Raise warning if the raising metric implied and calculated are not consistent.
    Eigen::MatrixXcd ShouldBeID = bas.first->loweringMetric*bas.first->raisingMetric;
    numType error = (ShouldBeID - Eigen::MatrixXcd::Identity(ShouldBeID.rows(),ShouldBeID.cols())).norm();
    if (error > 1e-11)
        logger().log("Warning added basis transformation and raising/lowering metric are inconsistent, Error", error);
}

std::pair<std::shared_ptr<BasisManager::Basis>,std::unique_lock<std::shared_mutex>> BasisManager::addBasis(const std::string &name, const std::string &parent,
                                                            const Eigen::MatrixXcd &parentToHereForwardTransform, bool isAutoGenerated,
                                                            const Eigen::MatrixXcd* hereToParentForwardTransformation /* = nullptr*/)
{
    //New basis with no links or it is autogenerated in which case it doesnt take part in the graph traversal
    //If a transformation is added by this while another thread deletes the parent the parent basis link will not be present in the graph but will not be properly deleted either.

    assert(!lookupBasis(name,true) || isAutoGenerated);
    std::shared_ptr<BasisManager::Basis> bas = std::make_shared<Basis>();
    std::shared_ptr<Basis> parentBasis = lookupBasis(parent,false);
    if (!parentBasis)
    {
        releaseAssert(false,"No Parent called: " + parent );
    }
    if constexpr(traceBasisCreations)
        logger().log("Creating basis: " + name + ", with parent: " + parent + (isAutoGenerated? ". Is " : ". Is not ") + "AutoGenerated");
    bas->name = name;
    bas->parentName = parent;
    bas->linkedNodes = {parentBasis};
    // If i is the parent and mu is the new basis
    // bas->parentToHereDirect = |e_\mu} = L_\mu^{i} |e_i>. Expected to be stored as L_{i\mu}

    // bas->hereToParentDirect= |e_i} = L_i^{\mu} |e_\mu>. Stored as L_{\mu i}
    if (hereToParentForwardTransformation == nullptr)
    {
        bas->parentToHereDirect = parentToHereForwardTransform;
        Basis::generateTransformations(bas->parentToHereDirect,bas->hereToParentDirect); // Does an SVD and cuts out small numbers
    }
    else
    {
        bas->parentToHereDirect = parentToHereForwardTransform;
        bas->hereToParentDirect = *hereToParentForwardTransformation;
    }
    bas->isAutoGenerated = isAutoGenerated;
    //  S_{\bar{\nu}\mu} = L^{\bar{j}}_{\bar{\nu}} L^{i}_{\mu} <e_\bar{j}|e_i>
    //  S^{\nu\bar{\mu}} = L_{j}^{\nu} L_\bar{i}^\bar{\mu} <e^j|e^\bar{i}>
    if (parentBasis->isOrthoNormal)
    {
        bas->loweringMetric.noalias() = bas->parentToHereDirect.adjoint() * bas->parentToHereDirect;
        bas->raisingMetric = bas->hereToParentDirect * bas->hereToParentDirect.adjoint(); //bas->loweringMetric.inverse();//TODO be clever about zeros
    }
    else
    {
        bas->loweringMetric.noalias() = bas->parentToHereDirect.adjoint() * parentBasis->loweringMetric * bas->parentToHereDirect;
        bas->raisingMetric = bas->hereToParentDirect * parentBasis->raisingMetric *bas->hereToParentDirect.adjoint();//bas->loweringMetric.inverse();//TODO be clever about zeros
    }

    std::unique_lock<std::shared_mutex> lock(m_basisLock);
    BasisManager::getInstance().m_BasisList.emplace_back(bas);
    parentBasis->linkedNodes.push_back(bas);
    return {bas,std::move(lock)};
}

std::shared_ptr<BasisManager::Basis> BasisManager::addProjection(const std::string &name, const std::string &parent, const Eigen::MatrixXcd &parentToHereForwardTransform, bool isAutoGenerated, const Eigen::MatrixXcd *hereToParentForwardTransformation)
{
    const std::pair<std::shared_ptr<BasisManager::Basis>,std::unique_lock<std::shared_mutex>>& bas
        = addBasis(name,parent,parentToHereForwardTransform,isAutoGenerated,hereToParentForwardTransformation);
    bas.first->isProjection = true;
    return bas.first;
}

std::shared_ptr<BasisManager::Basis> BasisManager::addProjectionOrthogonal(const std::string &name, const std::string &parent, const Eigen::MatrixXcd &parentToHereForwardTransform, bool isAutoGenerated, const Eigen::MatrixXcd *hereToParentForwardTransformation)
{
    std::pair<std::shared_ptr<BasisManager::Basis>,std::unique_lock<std::shared_mutex>> bas
        = addOrthogonalBasis(name,parent,parentToHereForwardTransform,isAutoGenerated,hereToParentForwardTransformation);
    bas.first->isProjection = true;
    return bas.first;
}

std::pair<std::shared_ptr<BasisManager::Basis>,std::unique_lock<std::shared_mutex>> BasisManager::addOrthogonalBasis(const std::string &name, const std::string &parent, const Eigen::MatrixXcd &parentToHereForwardTransform, bool isAutoGenerated, const Eigen::MatrixXcd* hereToParentForwardTransform /* = nullptr*/)
{
    std::pair<std::shared_ptr<BasisManager::Basis>,std::unique_lock<std::shared_mutex>>
        bas = addBasis(name,parent,parentToHereForwardTransform,isAutoGenerated,hereToParentForwardTransform);
    long dim = parentToHereForwardTransform.cols() ;
    bas.first->loweringMetric = Eigen::MatrixXcd::Identity(dim,dim);
    bas.first->raisingMetric = Eigen::MatrixXcd::Identity(dim,dim);
    bas.first->isOrthoNormal = true;

    return bas;
}

std::string gen_random(const int len) {
    static const char alphanum[] =
        "0123456789"
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "abcdefghijklmnopqrstuvwxyz";
    std::string tmp_s;
    tmp_s.reserve(len);

    for (int i = 0; i < len; ++i) {
        tmp_s += alphanum[rand() % (sizeof(alphanum) - 1)];
    }

    return tmp_s;
}

std::shared_ptr<std::string> BasisManager::addTemporaryBasis(const Eigen::MatrixXcd &loweringMetric)
{
    std::string guess = gen_random(12);
    while(lookupBasis(guess,false))
    {
        guess = gen_random(12);
    }
    addBasis(guess,loweringMetric);
    return std::shared_ptr<std::string>(new std::string(std::move(guess)),[](std::string* str){deleteBasis(*str); delete str;});
}

std::shared_ptr<std::string> BasisManager::addTemporaryBasis(const std::string &parent, const Eigen::MatrixXcd &parentToHereForwardTransform)
{
    std::string guess = gen_random(12);
    while(lookupBasis(guess,false))
    {
        guess = gen_random(12);
    }
    addBasis(guess,parent,parentToHereForwardTransform);
    return std::shared_ptr<std::string>(new std::string(std::move(guess)),[](std::string* str){deleteBasis(*str); delete str;});
}

std::shared_ptr<std::string> BasisManager::addTemporaryOrthogonalBasis(const std::string &parent, const Eigen::MatrixXcd &parentToHereForwardTransform)
{
    std::string guess = gen_random(12);
    while(lookupBasis(guess,false))
    {
        guess = gen_random(12);
    }
    addOrthogonalBasis(guess,parent,parentToHereForwardTransform);
    return std::shared_ptr<std::string>(new std::string(std::move(guess)),[](std::string* str){deleteBasis(*str); delete str;});
}

LoweringMetric BasisManager::getMetric(const std::string &basis)
{
    auto bas = lookupBasis(basis,true);//Metric is the same even if it is autogenerated
    if (!bas)
        return LoweringMetric();
    return LoweringMetric(bas->loweringMetric,basis,enums::SpinSymmetry::NoSpinSym);
}

bool BasisManager::isOrthogonal(const std::string &basis)
{
    auto bas = lookupBasis(basis,true);
    if (!bas)
        return false;
    return bas->isOrthoNormal;
}

void BasisManager::deleteBasis(const std::string &name)
{
    if (name == "")
    {
        logger().log("Cannot delete Null Basis");
        return;
    }
    auto& bm = getInstance();
    std::unique_lock<std::shared_mutex> lock(bm.m_basisLock);
    for (auto it = bm.m_BasisList.begin(); it != bm.m_BasisList.end(); )
    {
        if (sanitizeInput((*it)->name,true) == name)
        {
            lock = (*it)->cleanupMyself(std::move(lock));
            it = bm.m_BasisList.erase(it);
        }
        else
            ++it;
    }
}

void BasisManager::deleteAllBasis()
{
    auto& bm = getInstance();
    {
        std::unique_lock<std::shared_mutex> lock(bm.m_basisLock);
        for (const auto& bas : bm.m_BasisList)
        {
            lock = bas->cleanupAll(std::move(lock));
        }
        bm.m_BasisList.clear();
    }
    bm.makeNullBasis();
}

std::string BasisManager::buildCanonicalBasisString(std::string basis, std::vector<possibleTags> tags)
{
    std::sort(tags.begin(),tags.end());
    std::string canonical = sanitizeInput(basis,true); // This way it can be used to change the tags on a basis
    bool foundLowdin = false;
    bool foundBlock = false;
    for (const auto& t : tags)
    {
        switch (t)
        {
        case possibleTags::LowdinBasis:
            canonical += LowdinOrthogonaliseBasis;
            if (foundLowdin) {logger().log("Duplicate Lowdin basis tag"); return "";}
            foundLowdin = true;
            continue;
        case possibleTags::ABlock:
            canonical += Alpha_Block;
            if (foundBlock) {logger().log("Duplicate SpinBlock tag"); return "";}
            foundBlock = true;
            continue;
        case possibleTags::BBlock:
            canonical += Beta_Block;
            if (foundBlock) {logger().log("Duplicate SpinBlock tag"); return "";}
            foundBlock = true;
            continue;
        case possibleTags::NullBasis:
            continue;
        default:
            releaseAssert(false, "Unhandled Switch case");
        }
    }
    return canonical;
}

std::string BasisManager::buildCanonicalBasisString(std::string basis)
{
    std::vector<possibleTags> tags = checkForTags(basis);
    if (tags.size() == 0)
        return basis;
    basis = sanitizeInput(basis,true);
    return buildCanonicalBasisString(basis,tags);
}

std::string BasisManager::removeSpinTags(std::string basis, possibleTags* deletedTag)
{
    std::vector<possibleTags> tags = checkForTags(basis);
    if (tags.size() == 0)
        return basis;
    for (auto it = tags.begin(); it != tags.end();)
    {
        switch (*it)
        {
        case possibleTags::ABlock:
        case possibleTags::BBlock:
            if (deletedTag) *deletedTag = *it;
            it = tags.erase(it);
            continue;
        default:
            ++it;
            continue;
        }
    }
    basis = sanitizeInput(basis,true);
    return buildCanonicalBasisString(basis,tags);
}












